### ISSUE TITLE
How to detect if the console is open

### ISSUE THREAD

**Issue by Pau1fitz** [tholman/console-fright-night#2]
Hi Tim, 

just a quick question. In your code how are you detecting if the console has been opened?

I am unsure what these lines of code are doing:

```
 // When the console logs and is open, it requests the id.
    // We can jack into this, to tell when the console has been opened.
    audioElement.__defineGetter__('id', function() {
      audioCheck = true;
    });
```

Also, when I check the following lines in the chrome console each of these return undefined:

`(window.Firebug && window.Firebug.chrome && window.Firebug.chrome.isInitialized)`

In this code https://github.com/sindresorhus/devtools-detect/blob/gh-pages/index.js it is using either the method you have used above `(window.Firebug && window.Firebug.chrome && window.Firebug.chrome.isInitialized)` or else the way Paul Irish suggests here http://stackoverflow.com/questions/7527442/how-to-detect-chrome-inspect-element-is-running-or-not/15567735#15567735

It is unclear to me how CNF is detecting my console is open if the chrome version I am using doesn't recognise `(window.Firebug && window.Firebug.chrome && window.Firebug.chrome.isInitialized)`

**Comment by tholman** [comment]
Yo!

Right, in regards to 

```
audioElement.__defineGetter__('id', function() {
   audioCheck = true;
 });
```

When the console is open (in chrome) and it tries to log out an element, it checks the elements id -- using the get function. So here, we've hooked into that, and added our own functionality. When the console is closed, it doesn't need to render the element in the console, so the function isn't called.

The firebug stuff, is just a quick extra, incase someone is using firebug... it was added in because it was a tiny, easy addition. If you install firebug, it'd log true, when the firebug console is open :)
